image:
  repository: rayproject/ray-ml
  tag: 2.21.0
  pullPolicy: IfNotPresent
head:
  enableInTreeAutoscaling: true
  resources:
    limits:
      cpu: 4
      memory: 24G
    requests:
      cpu: 4
      memory: 12G
  tolerations:
  - key: ray-cluster
    effect: NoSchedule
    operator: Exists
  containerEnv:
  - name: RAY_LOG_TO_STDERR
    value: 1
  - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
    value: python
worker:
  resources:
    limits:
      cpu: 8
      memory: 24G
    requests:
      cpu: 4
      memory: 12G
  tolerations:
  - key: ray-cluster
    effect: NoSchedule
    operator: Exists
  containerEnv:
  - name: RAY_LOG_TO_STDERR
    value: 1
  - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
    value: python
  replicas: 0
  minReplicas: 0
  maxReplicas: 30