---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: argocd-pv
  labels:
    volume-name: argocd-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: $ARGOCD_PV
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-gp2-sc