apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: monitoring
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::948065143262:role/patrick-cloud-eks-external-secrets-sa-role
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: monitoring
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-credentials
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: grafana-credentials
    creationPolicy: Owner
  data:
  - secretKey: grafana_username
    remoteRef:
      key: GRAFANA_CREDENTIALS
      property: username
  - secretKey: grafana_password
    remoteRef:
      key: GRAFANA_CREDENTIALS
      property: password