persistence:
  enabled: true
  size: 2Gi
  storageClassName: ebs-gp2-sc
  accessModes:
    - ReadWriteOnce
  volumeName: pv-name
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server.monitoring.svc.cluster.local
admin:
  existingSecret: grafana-credentials
  userKey: grafana_username
  passwordKey: grafana_password
grafana.ini:
  server:
    domain: kubernetes.patrick-cloud.com
    protocol: http
    root_url: "%(protocol)s://%(domain)s/grafana/"