---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
  labels:
    volume-name: prometheus-server-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: $PROMETHEUS_SERVER_PV
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-gp2-sc