resources:
- config-map-aws-auth.yaml
- storage-class.yaml
- namespace.yaml

helmCharts:
- name: external-secrets
  repo: https://charts.external-secrets.io
  version: v0.9.17
  releaseName: external-secrets
  includeCRDs: true
  namespace: external-secrets