---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alert-manager-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: $ALERT_MANAGER_PROMETHEUS_PV
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-gp2-sc