apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp2-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: "gp2"