server:
  persistentVolume:
    size: 8Gi
    volumeName: prometheus-server-pv
    accessModes:
      - ReadWriteOnce
    storageClass: ebs-gp2-sc
    selector:
      matchLabels:
        volume-name: "prometheus-server-pv"
  extraArgs:
    web.external-url: http://kubernetes.patrick-cloud.com/prometheus
    web.route-prefix: /
extraScrapeConfigs: |
  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
    - targets: 
      - jenkins.patrick-cloud.com
  - job_name: 'node_exporter'
    static_configs:
    - targets: 
      - prometheus-prometheus-node-exporter.monitoring.svc.cluster.local:9100
  - job_name: istiod
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - istio-system
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: istiod;http-monitoring
  - job_name: envoy-stats
    metrics_path: /stats/prometheus
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: '.*-envoy-prom'
  - job_name: grafana
    static_configs:
    - targets:
      - grafana.monitoring.svc.cluster.local
  - job_name: karpenter
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - karpenter
    relabel_configs:
    - source_labels:
      - __meta_kubernetes_endpoints_name
      - __meta_kubernetes_endpoint_port_name
      action: keep
      regex: karpenter;http-metrics
alertmanager:
  persistence:
    size: 2Gi
    storageClass: ebs-gp2-sc
    volumeName: prometheus-alert-manager-pv
    selector:
      matchLabels:
        volume-name: "prometheus-alert-manager-pv"