image:
  repository: rayproject/ray-ml
  tag: 2.21.0-cpu
  pullPolicy: IfNotPresent
head:
  enableInTreeAutoscaling: true
  resources:
    limits:
      cpu: 4
      memory: 24G
    requests:
      cpu: 4
      memory: 12G
  nodeSelector:
    NodePool: ray-cluster-head
  tolerations:
  - key: cluster-name
    value: ray-cluster-head
    operator: "Equal"
    effect: NoSchedule
  containerEnv:
  - name: RAY_LOG_TO_STDERR
    value: "1"
  - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
    value: python
worker:
  resources:
    limits:
      cpu: 8
      memory: 24G
    requests:
      cpu: 4
      memory: 12G
  nodeSelector:
    NodePool: ray-cluster-worker
  tolerations:
  - key: cluster-name
    value: ray-cluster-worker
    operator: "Equal"
    effect: NoSchedule
  containerEnv:
  - name: RAY_LOG_TO_STDERR
    value: "1"
  - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
    value: python
  replicas: 1
  minReplicas: 1
  maxReplicas: 3