apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: patrick-cloud-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Project for all Patrick-Cloud applications

  # Allow manifests to deploy from only patrick-cloud Git repos
  sourceRepos:
  - 'https://github.com/patrickoconnor80/patrick-cloud-*'

  # Allow all kubectl actions for now (TODO restrict permissiosn to least permissive)
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  # Only permit applications to deploy to the guestbook namespace in the same cluster
  # Destination clusters can be identified by 'server', 'name', or both.
  destinations:
  - namespace: dbt-docs
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: game-2048
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: monitoring
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: istio-system
    server: https://kubernetes.default.svc
    name: in-cluster