resources:
- argo-cd-crds.yaml
- namespace.yaml
- istio-virtual-services.yaml
- argo-cd-projects.yaml
- argo-cd-applications.yaml

helmCharts:
- name: argo-cd
  repo: https://argoproj.github.io/argo-helm
  version: v3.35.4
  namespace: argocd
  #valuesFile: helm-values/argo-cd-values.yaml
  valuesInline:
    configs:
      params:
        server:
          rootpath: /argocd
          basehref: /argocd
          insecure: true

# patches:
# - path: patch.yaml

namespace: argocd