backendStore:
  postgres: 
    enabled: true
    host: temp_host
    database: mlflow
    port: 5432
    user: postgres
    password: temp_pasword
artifactRoot:
  s3:
    enabled: true
    bucket: patrick-cloud-$ENV-mlflow-artifact-root
extraSecretNamesForEnvFrom:
- mlflow-tracking-uri
- mlflow-tracking-password
serviceAccount:
  create: true
  name: mlflow-sa
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::$ACCOUNT_ID:role/patrick-cloud-$ENV-eks-mlflow-sa-role