backendStore:
  postgres: 
    enabled: true
    host: temp_host
    database: mlflow
    port: 5432
    user: postgres
    password: temp_pasword
artifactRoot:
  s3:
    enabled: true
    bucket: s3:://patrick-cloud-$ENV-mlflow-artifact-root
extraSecretNamesForEnvFrom:
- name: MLFLOW_TRACKING_URI
  valueFrom:
    secretKeyRef:
      name: mlfow-tracking-uri
      key: MLFLOW_TRACKING_URI
- name: MLFLOW_TRACKING_PASSWORD
  valueFrom:
    secretKeyRef:
      name: mlfow-tracking-password
      key: MLFLOW_TRACKING_PASSWORD