---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub-sa
  namespace: jupyterhub
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$ACCOUNT_ID:role/patrick-cloud-$ENV-eks-jupyterhub-sa-role