# Setting up a subpath on Istio - see documentation
# https://argo-cd.readthedocs.io/en/stable/operator-manual/ingress/#istio
configs:
  params:
    server.rootpath: /argocd
    server.basehref: /argocd
    server.insecure: true
persistence:
  enabled: true
  size: 2Gi
  storageClassName: ebs-gp2-sc
  # accessModes:
  #   - ReadWriteOnce
  # volumeName: argocd-pv
  # selectorLabels:
  #   volume-name: argocd-pv