server:
  persistentVolume:
    size: 8Gi
    volumeName: prometheus-server-pv
    accessModes:
      - ReadWriteOnce
    storageClass: ebs-gp2-sc
    selector:
      matchLabels:
        volume-name: "prometheus-server-pv"
  extraArgs:
    web.external-url: http://kubernetes.patrick-cloud.com/prometheus
    web.route-prefix: /
extraScrapeConfigs:
  - job_name: 'jenkins'
  metrics_path: '/prometheus'
  static_configs:
    - targets: 
      - 3.90.0.250:8080
alertmanager:
  persistence:
    size: 2Gi
    storageClass: ebs-gp2-sc
    volumeName: prometheus-alert-manager-pv
    selector:
      matchLabels:
        volume-name: "prometheus-alert-manager-pv"