resources:
- namespace.yaml
- volumes.yaml
- external-secrets.yaml
- istio-virtual-services.yaml

helmCharts:
- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  version: v.25.18.10
  releaseName: prometheus
  namespace: monitoring
  valuesFile: helm-values/prometheus-values.yaml
- name: grafana
  repo: https://grafana.github.io/helm-charts
  version: v.7.3.7
  releaseName: grafana
  namespace: monitoring
  valuesFile: helm-values/grafana-values.yaml

namespace: monitoring