---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  labels:
    volume-name: grafana-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-070d1fc644d5fd710 #grafana-tag
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-gp2-sc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alert-manager-pv
  labels:
    volume-name: prometheus-alert-manager-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-01bac9a96f0a172df #prometheus-alert-manager-tag
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-gp2-sc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
  labels:
    volume-name: prometheus-server-pv
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0e3d3d0176410f6a0 #prometheus-server-tag
  capacity:
    storage: 8Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-gp2-sc