---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: mlflow
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::$ACCOUNT_ID:role/patrick-cloud-$ENV-eks-mlflow-external-secrets-sa-role
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: mlflow
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-tracking-uri
  namespace: mlflow
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: mlflow-tracking-uri
    creationPolicy: Owner
  data:
  - secretKey: PGHOST
    remoteRef:
      key: MLFLOW_TRACKING_URI
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-tracking-password
  namespace: mlflow
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: mlflow-tracking-password
    creationPolicy: Owner
  data:
  - secretKey: PGPASSWORD
    remoteRef:
      key: MLFLOW_TRACKING_PASSWORD